// Generated by Supabase CLI
// Do not modify manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      alerts: {
        Row: {
          acknowledged: boolean | null
          acknowledged_at: string | null
          acknowledged_by: string | null
          id: string
          message: string
          session_id: string
          triggered_at: string
          type: string
        }
        Insert: {
          acknowledged?: boolean | null
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          id?: string
          message: string
          session_id: string
          triggered_at?: string
          type: string
        }
        Update: {
          acknowledged?: boolean | null
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          id?: string
          message?: string
          session_id?: string
          triggered_at?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "alerts_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "cooling_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      compliance_reports: {
        Row: {
          compliant_temp_readings: number | null
          cooling_compliance_rate: number | null
          created_at: string | null
          discarded_sessions: number | null
          exception_sessions: number | null
          id: string
          late_sessions: number | null
          manager_notes: string | null
          non_compliant_temp_readings: number | null
          on_time_sessions: number | null
          overall_compliance_rate: number | null
          pdf_url: string | null
          report_data: Json | null
          report_date: string
          report_type: string
          reviewed_at: string | null
          reviewed_by: string | null
          reviewed_by_name: string | null
          site_id: string
          status: string | null
          temp_compliance_rate: number | null
          total_cooling_sessions: number | null
          total_temp_readings: number | null
          updated_at: string | null
        }
        Insert: {
          compliant_temp_readings?: number | null
          cooling_compliance_rate?: number | null
          created_at?: string | null
          discarded_sessions?: number | null
          exception_sessions?: number | null
          id?: string
          late_sessions?: number | null
          manager_notes?: string | null
          non_compliant_temp_readings?: number | null
          on_time_sessions?: number | null
          overall_compliance_rate?: number | null
          pdf_url?: string | null
          report_data?: Json | null
          report_date: string
          report_type?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          reviewed_by_name?: string | null
          site_id: string
          status?: string | null
          temp_compliance_rate?: number | null
          total_cooling_sessions?: number | null
          total_temp_readings?: number | null
          updated_at?: string | null
        }
        Update: {
          compliant_temp_readings?: number | null
          cooling_compliance_rate?: number | null
          created_at?: string | null
          discarded_sessions?: number | null
          exception_sessions?: number | null
          id?: string
          late_sessions?: number | null
          manager_notes?: string | null
          non_compliant_temp_readings?: number | null
          on_time_sessions?: number | null
          overall_compliance_rate?: number | null
          pdf_url?: string | null
          report_data?: Json | null
          report_date?: string
          report_type?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          reviewed_by_name?: string | null
          site_id?: string
          status?: string | null
          temp_compliance_rate?: number | null
          total_cooling_sessions?: number | null
          total_temp_readings?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "compliance_reports_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "staff_members"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "compliance_reports_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      cooling_events: {
        Row: {
          created_at: string | null
          event_type: string
          id: string
          payload: Json | null
          session_id: string
          site_id: string
          timestamp: string
        }
        Insert: {
          created_at?: string | null
          event_type: string
          id?: string
          payload?: Json | null
          session_id: string
          site_id: string
          timestamp?: string
        }
        Update: {
          created_at?: string | null
          event_type?: string
          id?: string
          payload?: Json | null
          session_id?: string
          site_id?: string
          timestamp?: string
        }
        Relationships: [
          {
            foreignKeyName: "cooling_events_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "cooling_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cooling_events_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      cooling_sessions: {
        Row: {
          close_action: string | null
          closed_at: string | null
          closed_by: string | null
          closed_by_id: string | null
          created_at: string | null
          created_by: string | null
          end_temperature: number | null
          exception_approved_by: string | null
          exception_reason: string | null
          food_item_id: string | null
          hard_due_at: string
          id: string
          item_category: string
          item_name: string
          site_id: string
          soft_due_at: string
          staff_name: string | null
          start_temperature: number | null
          started_at: string
          started_by_id: string | null
          status: string
          updated_at: string | null
        }
        Insert: {
          close_action?: string | null
          closed_at?: string | null
          closed_by?: string | null
          closed_by_id?: string | null
          created_at?: string | null
          created_by?: string | null
          end_temperature?: number | null
          exception_approved_by?: string | null
          exception_reason?: string | null
          food_item_id?: string | null
          hard_due_at: string
          id?: string
          item_category?: string
          item_name: string
          site_id: string
          soft_due_at: string
          staff_name?: string | null
          start_temperature?: number | null
          started_at?: string
          started_by_id?: string | null
          status?: string
          updated_at?: string | null
        }
        Update: {
          close_action?: string | null
          closed_at?: string | null
          closed_by?: string | null
          closed_by_id?: string | null
          created_at?: string | null
          created_by?: string | null
          end_temperature?: number | null
          exception_approved_by?: string | null
          exception_reason?: string | null
          food_item_id?: string | null
          hard_due_at?: string
          id?: string
          item_category?: string
          item_name?: string
          site_id?: string
          soft_due_at?: string
          staff_name?: string | null
          start_temperature?: number | null
          started_at?: string
          started_by_id?: string | null
          status?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "cooling_sessions_closed_by_id_fkey"
            columns: ["closed_by_id"]
            isOneToOne: false
            referencedRelation: "staff_members"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cooling_sessions_food_item_id_fkey"
            columns: ["food_item_id"]
            isOneToOne: false
            referencedRelation: "food_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cooling_sessions_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cooling_sessions_started_by_id_fkey"
            columns: ["started_by_id"]
            isOneToOne: false
            referencedRelation: "staff_members"
            referencedColumns: ["id"]
          },
        ]
      }
      sites: {
        Row: {
          address: string | null
          alert_email: string | null
          alert_phone: string | null
          created_at: string | null
          id: string
          kiosk_pin: string | null
          name: string
          subscription_tier: 'basic' | 'pro' | 'enterprise' | null
          updated_at: string | null
        }
        Insert: {
          address?: string | null
          alert_email?: string | null
          alert_phone?: string | null
          created_at?: string | null
          id?: string
          kiosk_pin?: string | null
          name: string
          subscription_tier?: 'basic' | 'pro' | 'enterprise' | null
          updated_at?: string | null
        }
        Update: {
          address?: string | null
          alert_email?: string | null
          alert_phone?: string | null
          created_at?: string | null
          id?: string
          kiosk_pin?: string | null
          name?: string
          subscription_tier?: 'basic' | 'pro' | 'enterprise' | null
          updated_at?: string | null
        }
        Relationships: []
      }
      staff_members: {
        Row: {
          id: string
          site_id: string
          name: string
          role: 'manager' | 'chef' | 'staff'
          initials: string | null
          pin: string | null
          staff_code: string | null
          active: boolean | null
          email: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          site_id: string
          name: string
          role?: 'manager' | 'chef' | 'staff'
          initials?: string | null
          pin?: string | null
          staff_code?: string | null
          active?: boolean | null
          email?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          site_id?: string
          name?: string
          role?: 'manager' | 'chef' | 'staff'
          initials?: string | null
          pin?: string | null
          staff_code?: string | null
          active?: boolean | null
          email?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      food_items: {
        Row: {
          id: string
          site_id: string | null
          name: string
          category: 'sauce' | 'soup' | 'meat' | 'vegetable' | 'other'
          icon: string | null
          use_count: number | null
          created_at: string
        }
        Insert: {
          id?: string
          site_id?: string | null
          name: string
          category: 'sauce' | 'soup' | 'meat' | 'vegetable' | 'other'
          icon?: string | null
          use_count?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          site_id?: string | null
          name?: string
          category?: 'sauce' | 'soup' | 'meat' | 'vegetable' | 'other'
          icon?: string | null
          use_count?: number | null
          created_at?: string
        }
      }
      compliance_logs: {
        Row: {
            id: string
            site_id: string | null
            schema_id: string
            data: Json
            status: 'pass' | 'fail' | 'rectified' | 'pending' | null
            source: 'app' | 'voice' | 'iot_sensor' | 'manager_audit' | null
            created_at: string | null
            user_id: string | null
        }
        Insert: {
            id?: string
            site_id?: string | null
            schema_id: string
            data: Json
            status?: 'pass' | 'fail' | 'rectified' | 'pending' | null
            source?: 'app' | 'voice' | 'iot_sensor' | 'manager_audit' | null
            created_at?: string | null
            user_id?: string | null
        }
        Update: {
            id?: string
            site_id?: string | null
            schema_id?: string
            data?: Json
            status?: 'pass' | 'fail' | 'rectified' | 'pending' | null
            source?: 'app' | 'voice' | 'iot_sensor' | 'manager_audit' | null
            created_at?: string | null
            user_id?: string | null
        }
      }
      goods_receipts: {
        Row: {
          id: string
          site_id: string
          supplier_name: string
          invoice_number: string | null
          invoice_date: string | null
          received_by_staff_id: string | null
          received_by_name: string
          received_at: string
          overall_temperature: number | null
          temperature_compliant: boolean | null
          ocr_raw_text: string | null
          ocr_confidence: number | null
          invoice_image_url: string | null
          notes: string | null
          status: 'draft' | 'completed' | 'flagged' | 'voided' | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          site_id: string
          supplier_name: string
          invoice_number?: string | null
          invoice_date?: string | null
          received_by_staff_id?: string | null
          received_by_name: string
          received_at?: string
          overall_temperature?: number | null
          temperature_compliant?: boolean | null
          ocr_raw_text?: string | null
          ocr_confidence?: number | null
          invoice_image_url?: string | null
          notes?: string | null
          status?: 'draft' | 'completed' | 'flagged' | 'voided' | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          site_id?: string
          supplier_name?: string
          invoice_number?: string | null
          invoice_date?: string | null
          received_by_staff_id?: string | null
          received_by_name?: string
          received_at?: string
          overall_temperature?: number | null
          temperature_compliant?: boolean | null
          ocr_raw_text?: string | null
          ocr_confidence?: number | null
          invoice_image_url?: string | null
          notes?: string | null
          status?: 'draft' | 'completed' | 'flagged' | 'voided' | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "goods_receipts_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goods_receipts_received_by_staff_id_fkey"
            columns: ["received_by_staff_id"]
            isOneToOne: false
            referencedRelation: "staff_members"
            referencedColumns: ["id"]
          },
        ]
      }
      goods_receipt_items: {
        Row: {
          id: string
          receipt_id: string
          item_name: string
          quantity: number
          unit: string | null
          temperature: number | null
          temperature_compliant: boolean | null
          category: 'chilled' | 'frozen' | 'ambient' | 'dry' | 'produce' | 'meat' | 'dairy' | 'seafood' | null
          notes: string | null
          sort_order: number | null
          created_at: string | null
        }
        Insert: {
          id?: string
          receipt_id: string
          item_name: string
          quantity?: number
          unit?: string | null
          temperature?: number | null
          temperature_compliant?: boolean | null
          category?: 'chilled' | 'frozen' | 'ambient' | 'dry' | 'produce' | 'meat' | 'dairy' | 'seafood' | null
          notes?: string | null
          sort_order?: number | null
          created_at?: string | null
        }
        Update: {
          id?: string
          receipt_id?: string
          item_name?: string
          quantity?: number
          unit?: string | null
          temperature?: number | null
          temperature_compliant?: boolean | null
          category?: 'chilled' | 'frozen' | 'ambient' | 'dry' | 'produce' | 'meat' | 'dairy' | 'seafood' | null
          notes?: string | null
          sort_order?: number | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "goods_receipt_items_receipt_id_fkey"
            columns: ["receipt_id"]
            isOneToOne: false
            referencedRelation: "goods_receipts"
            referencedColumns: ["id"]
          },
        ]
      }
      customers: {
        Row: {
          id: string
          owner_name: string
          email: string
          phone: string | null
          restaurant_name: string
          restaurant_type: string | null
          address: string | null
          city: string | null
          country: string | null
          subscription_tier: 'tier1' | 'tier2' | 'tier3'
          trial_ends_at: string | null
          status: 'trial' | 'active' | 'cancelled' | 'expired' | 'pending'
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          branding_enabled: boolean | null
          brand_logo_url: string | null
          brand_primary_color: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          owner_name: string
          email: string
          phone?: string | null
          restaurant_name: string
          restaurant_type?: string | null
          address?: string | null
          city?: string | null
          country?: string | null
          subscription_tier?: 'tier1' | 'tier2' | 'tier3'
          trial_ends_at?: string | null
          status?: 'trial' | 'active' | 'cancelled' | 'expired' | 'pending'
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          branding_enabled?: boolean | null
          brand_logo_url?: string | null
          brand_primary_color?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          owner_name?: string
          email?: string
          phone?: string | null
          restaurant_name?: string
          restaurant_type?: string | null
          address?: string | null
          city?: string | null
          country?: string | null
          subscription_tier?: 'tier1' | 'tier2' | 'tier3'
          trial_ends_at?: string | null
          status?: 'trial' | 'active' | 'cancelled' | 'expired' | 'pending'
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          branding_enabled?: boolean | null
          brand_logo_url?: string | null
          brand_primary_color?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      venues: {
        Row: {
          id: string
          name: string
          address: string | null
          city: string | null
          country: string | null
          venue_type: string | null
          seating_capacity: number | null
          avg_daily_covers: number | null
          number_of_staff: number | null
          has_kitchen_manager: boolean | null
          compliance_method: string | null
          main_pain_point: string | null
          opening_date: string | null
          created_by: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          name: string
          address?: string | null
          city?: string | null
          country?: string | null
          venue_type?: string | null
          seating_capacity?: number | null
          avg_daily_covers?: number | null
          number_of_staff?: number | null
          has_kitchen_manager?: boolean | null
          compliance_method?: string | null
          main_pain_point?: string | null
          opening_date?: string | null
          created_by?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          address?: string | null
          city?: string | null
          country?: string | null
          venue_type?: string | null
          seating_capacity?: number | null
          avg_daily_covers?: number | null
          number_of_staff?: number | null
          has_kitchen_manager?: boolean | null
          compliance_method?: string | null
          main_pain_point?: string | null
          opening_date?: string | null
          created_by?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          id: string
          email: string
          role: string | null
          current_venue_id: string | null
          onboarding_completed: boolean | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id: string
          email: string
          role?: string | null
          current_venue_id?: string | null
          onboarding_completed?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          email?: string
          role?: string | null
          current_venue_id?: string | null
          onboarding_completed?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_current_venue_id_fkey"
            columns: ["current_venue_id"]
            isOneToOne: false
            referencedRelation: "venues"
            referencedColumns: ["id"]
          },
        ]
      }
      venue_members: {
        Row: {
          id: string
          venue_id: string
          user_id: string
          role: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          venue_id: string
          user_id: string
          role?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          venue_id?: string
          user_id?: string
          role?: string | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "venue_members_venue_id_fkey"
            columns: ["venue_id"]
            isOneToOne: false
            referencedRelation: "venues"
            referencedColumns: ["id"]
          },
        ]
      }
      delivery_images: {
        Row: {
          id: string
          receipt_id: string
          image_type: 'delivery_note' | 'protein_label' | 'temperature_log' | 'other'
          storage_path: string
          original_filename: string | null
          compressed_size_bytes: number | null
          original_size_bytes: number | null
          mime_type: string | null
          page_number: number | null
          description: string | null
          product_name: string | null
          batch_number: string | null
          use_by_date: string | null
          supplier_code: string | null
          ocr_processed: boolean | null
          ocr_text: string | null
          captured_at: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          receipt_id: string
          image_type: 'delivery_note' | 'protein_label' | 'temperature_log' | 'other'
          storage_path: string
          original_filename?: string | null
          compressed_size_bytes?: number | null
          original_size_bytes?: number | null
          mime_type?: string | null
          page_number?: number | null
          description?: string | null
          product_name?: string | null
          batch_number?: string | null
          use_by_date?: string | null
          supplier_code?: string | null
          ocr_processed?: boolean | null
          ocr_text?: string | null
          captured_at?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          receipt_id?: string
          image_type?: 'delivery_note' | 'protein_label' | 'temperature_log' | 'other'
          storage_path?: string
          original_filename?: string | null
          compressed_size_bytes?: number | null
          original_size_bytes?: number | null
          mime_type?: string | null
          page_number?: number | null
          description?: string | null
          product_name?: string | null
          batch_number?: string | null
          use_by_date?: string | null
          supplier_code?: string | null
          ocr_processed?: boolean | null
          ocr_text?: string | null
          captured_at?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "delivery_images_receipt_id_fkey"
            columns: ["receipt_id"]
            isOneToOne: false
            referencedRelation: "goods_receipts"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Simplified type helpers
export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"]
export type TablesInsert<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Update"]

// Convenience type aliases for kitchen compliance
export type Site = Tables<'sites'>
export type StaffMember = Tables<'staff_members'>
export type FoodItem = Tables<'food_items'>
export type CoolingSession = Tables<'cooling_sessions'>
export type CoolingEvent = Tables<'cooling_events'>
export type Alert = Tables<'alerts'>
export type ComplianceReport = Tables<'compliance_reports'>
export type ComplianceLog = Tables<'compliance_logs'>
export type Customer = Tables<'customers'>
export type GoodsReceipt = Tables<'goods_receipts'>
export type GoodsReceiptItem = Tables<'goods_receipt_items'>
export type Venue = Tables<'venues'>
export type Profile = Tables<'profiles'>
export type VenueMember = Tables<'venue_members'>
export type DeliveryImage = Tables<'delivery_images'>

// Insert types
export type StaffMemberInsert = TablesInsert<'staff_members'>
export type FoodItemInsert = TablesInsert<'food_items'>
export type CoolingSessionInsert = TablesInsert<'cooling_sessions'>
export type CustomerInsert = TablesInsert<'customers'>
export type GoodsReceiptInsert = TablesInsert<'goods_receipts'>
export type GoodsReceiptItemInsert = TablesInsert<'goods_receipt_items'>
export type VenueInsert = TablesInsert<'venues'>
export type ProfileInsert = TablesInsert<'profiles'>
export type VenueMemberInsert = TablesInsert<'venue_members'>
export type DeliveryImageInsert = TablesInsert<'delivery_images'>

// Update types
export type CoolingSessionUpdate = TablesUpdate<'cooling_sessions'>
export type StaffMemberUpdate = TablesUpdate<'staff_members'>
export type CustomerUpdate = TablesUpdate<'customers'>
export type GoodsReceiptUpdate = TablesUpdate<'goods_receipts'>
export type GoodsReceiptItemUpdate = TablesUpdate<'goods_receipt_items'>
export type VenueUpdate = TablesUpdate<'venues'>
export type ProfileUpdate = TablesUpdate<'profiles'>
export type VenueMemberUpdate = TablesUpdate<'venue_members'>
